[project]
name = "perceptron"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ricardoestevam10", email = "rickysilva04205@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
perceptron = "perceptron:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "notebook>=7.6.3",
]
